#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: 12-del-runs
permissions: write-all
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
        
# 定时触发编译(每月第1天，6点 开始编译)
  schedule:
    - cron: 16 16 31 * *

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 准备完成
      uses: actions/checkout@main

    - name: 初始化系统环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"         
    
   # - name: 删除运行记录
      #uses: Mattraks/delete-workflow-runs@main
     # with:
        
    
       # repository: ${{ github.repository }}
       # retain_days: 16
        #keep_minimum_runs: 0
      #env:
      #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Delete workflow runs
      uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
      with:
      #  repository: popalanluck/delete-old-workflow-runs   # replace this with your own repository
       repository: ${{ github.repository }}
       older-than-seconds: 86400                           # remove all workflow runs older than 1 day
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        
   
